//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace puzzCode.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puzzCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 /* from: github.com/Zer0Mem0ry/RunPE/blob/master/RunPE.cpp
        /// * payload: {EXECUTABLE_FILE_PATH}
        /// */
        ///#include &lt;stdio.h&gt;
        ///#include &lt;Windows.h&gt;
        ///
        ///int RunPortableExecutable(void* Image)
        ///{
        ///    IMAGE_DOS_HEADER* DOSHeader;
        ///    IMAGE_NT_HEADERS* NtHeader;
        ///    IMAGE_SECTION_HEADER* SectionHeader;
        ///
        ///    PROCESS_INFORMATION PI;
        ///    STARTUPINFOA SI;
        ///
        ///    CONTEXT* CTX;
        ///
        ///    DWORD* ImageBase; //Base address of the image
        ///    void* pImageBase; // Pointer to the image base
        ///
        ///    int count;
        ///    char CurrentFi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string templateInjectSrc {
            get {
                return ResourceManager.GetString("templateInjectSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 #include &lt;time.h&gt; 
        ///#include &lt;stdio.h&gt;    
        ///#include &lt;windows.h&gt;
        ///
        ///void play(void) {
        ///    int code = rand() % 3;
        ///    switch (code)
        ///    {
        ///      case 0:
        ///        MessageBoxA(0, &quot;hello&quot;, &quot;info&quot;, 0);
        ///        break;
        ///      case 1:
        ///        MessageBoxA(0, &quot;hola&quot;, &quot;info&quot;, 0);
        ///        break;
        ///      default:
        ///        MessageBoxA(0, &quot;:/ ...&quot;, &quot;info&quot;, 0);
        ///        break;
        ///    }
        ///}    
        ///
        ///int main(int argc, char ** argv) {          
        ///    srand(time(0));
        ///    play();  
        ///    return 0;                                [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string templateSrc {
            get {
                return ResourceManager.GetString("templateSrc", resourceCulture);
            }
        }
    }
}
